# Generated by Django 4.2 on 2025-05-16 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proyek",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nama", models.CharField(max_length=250)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SQL", "SQL"),
                            ("Power BI", "Power BI"),
                            ("Tableau", "Tableau"),
                            ("Python Dash", "Python Dash"),
                            ("Python Django", "Python Django"),
                            ("Data Science", "Data Sciance"),
                        ],
                        max_length=250,
                    ),
                ),
                ("gambar", models.ImageField(blank=True, upload_to="media")),
                ("gambar2", models.ImageField(blank=True, upload_to="media")),
                ("gambar3", models.ImageField(blank=True, upload_to="media")),
                ("gambar4", models.ImageField(blank=True, upload_to="media")),
                ("tanggal", models.DateField(default=django.utils.timezone.now)),
                ("client", models.CharField(max_length=55)),
                ("output", models.URLField(default="a")),
                ("detail", models.URLField(default="a")),
                ("slug", models.SlugField(blank=True, editable=False)),
            ],
        ),
    ]
