# Generated by Django 5.2.3 on 2025-07-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyek',
            name='embed',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
