# Generated by Django 5.2.3 on 2025-07-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_proyek_embed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyek',
            name='category',
            field=models.CharField(choices=[('SQL', 'SQL'), ('Power-BI', 'Power BI'), ('Tableau', 'Tableau'), ('Python-Dash', 'Python Dash'), ('Python-Django', 'Python Django'), ('Data-Science', 'Data Sciance')], max_length=250),
        ),
    ]
