# Generated by Django 5.2.3 on 2025-07-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_proyek_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyek',
            name='category',
            field=models.CharField(choices=[('SQL', 'SQL'), ('Power-BI', 'Power BI'), ('Tableau', 'Tableau'), ('Dash', 'Python Dash'), ('Django', 'Python Django'), ('Data-Science', 'Data Sciance')], max_length=250),
        ),
    ]
