# Generated by Django 5.2.9 on 2026-05-20 07:34

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_proyek_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyek',
            name='github',
            field=models.URLField(default='a'),
        ),
        migrations.AlterField(
            model_name='proyek',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Excel', 'Excel'), ('SQL', 'SQL'), ('Power-BI', 'Power BI'), ('Tableau', 'Tableau'), ('Streamlit', 'Streamlit'), ('Python', 'Python'), ('Django', 'Django')], max_length=250),
        ),
    ]
