# Generated by Django 5.2.9 on 2026-05-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_proyek_github_alter_proyek_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyek',
            name='detail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyek',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyek',
            name='output',
            field=models.URLField(blank=True, null=True),
        ),
    ]
