# Generated by Django 4.2 on 2025-05-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_skill", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="img")),
            ],
        ),
    ]
