# Generated by Django 4.2 on 2025-05-14 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skill", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="skill",
            new_name="listskill",
        ),
    ]
