# Generated by Django 4.2 on 2025-05-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill", "0002_rename_skill_listskill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listskill",
            name="image",
            field=models.ImageField(upload_to="media/img"),
        ),
    ]
