# Generated by Django 4.2 on 2025-05-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill", "0004_alter_listskill_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listskill",
            name="image",
            field=models.ImageField(upload_to="samsul"),
        ),
    ]
